# Generated by Django 4.1 on 2022-08-15 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marcatarjeta",
            fields=[
                (
                    "marcaid",
                    models.AutoField(
                        db_column="MarcaId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "MarcaTarjeta",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                (
                    "numerotarjeta",
                    models.AutoField(
                        db_column="NumeroTarjeta", primary_key=True, serialize=False
                    ),
                ),
                ("cvv", models.IntegerField(blank=True, db_column="CVV", null=True)),
                ("fecha_de_otorgamiento", models.DateField()),
                ("fecha_de_expiracion", models.DateField()),
                ("tipo_tarjeta", models.TextField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Clientes.cliente",
                    ),
                ),
                (
                    "marcaid",
                    models.ForeignKey(
                        db_column="marcaId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Tarjetas.marcatarjeta",
                    ),
                ),
            ],
            options={
                "db_table": "tarjeta",
                "managed": True,
            },
        ),
    ]
