# Generated by Django 4.1 on 2022-08-15 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.TextField()),
                ("customer_surname", models.TextField()),
                (
                    "customer_dni",
                    models.TextField(db_column="customer_DNI", unique=True),
                ),
                ("dob", models.TextField(blank=True, null=True)),
                ("branch_id", models.IntegerField()),
            ],
            options={
                "db_table": "cliente",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_name", models.TextField()),
                ("employee_surname", models.TextField()),
                ("employee_hire_date", models.TextField()),
                ("employee_dni", models.TextField(db_column="employee_DNI")),
                ("branch_id", models.IntegerField()),
            ],
            options={
                "db_table": "empleado",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                ("branch_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch_number", models.BinaryField()),
                ("branch_name", models.TextField()),
                ("branch_address_id", models.IntegerField()),
            ],
            options={
                "db_table": "sucursal",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tiposclientes",
            fields=[
                (
                    "tipoid",
                    models.AutoField(
                        db_column="TipoId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "TiposClientes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Direcciones",
            fields=[
                ("calle", models.TextField(primary_key=True, serialize=False)),
                ("numero", models.IntegerField()),
                ("ciudad", models.TextField()),
                ("provincia", models.TextField()),
                ("pais", models.TextField()),
                (
                    "branch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Clientes.sucursal",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Clientes.cliente",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Clientes.empleado",
                    ),
                ),
            ],
            options={
                "db_table": "direcciones",
                "managed": True,
            },
        ),
    ]
